### ISSUE TITLE
fix: tests on MacOS 13.3.1 (a) (22E772610a)

### ISSUE THREAD

**Issue by metaist** [metaist/ezq#9]
Although this is isn't one of my preferred platforms, it'd be nice to let people know what's happening.

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/ezq/src/ezq/__init__.py", line 197, in __getattr__
    return getattr(self.q, name)
  File "/ezq/src/ezq/__init__.py", line 197, in __getattr__
    return getattr(self.q, name)
  File "/ezq/src/ezq/__init__.py", line 197, in __getattr__
    return getattr(self.q, name)
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by metaist** [comment]
```
FAILED test/test_ezq.py::test_run_processes - AssertionError: expect sum of 499500 from processes
FAILED test/test_ezq.py::test_map - AttributeError: Can't pickle local object 'map.<locals>.worker'
FAILED test/test_iter.py::test_iter_q - NotImplementedError
```

**Comment by metaist** [comment]
Ok, well the `NotImplementedError` comes from here:

```python
# multiprocessing.queues.Queue
def qsize(self):
        # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
```

**Comment by metaist** [comment]
Oh, goodness. https://stackoverflow.com/questions/67796535/why-multiprocess-works-differently-in-ubuntu-vs-macos

**Comment by metaist** [comment]
For future reference, see the [relevant python docs](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods):

> _Changed in version 3.8_: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See [bpo-33725](https://bugs.python.org/issue?@action=redirect&bpo=33725).

This created a whole new set of problems which is why I ultimately adopted [`multiprocess`](https://github.com/uqfoundation/multiprocess) over `multiprocessing`.
